name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [v1.x, canary]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build
        run: deno run --reload index.ts
      - name: Test
        run: deno test

